/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'returnFunds' : IDL.Null,
  'withdraw' : IDL.Null,
  'arbitration' : IDL.Null,
  'instantBuy' : IDL.Null,
  'recharge' : IDL.Null,
  'instantBuyReturn' : IDL.Null,
  'invest' : IDL.Null,
  'payout' : IDL.Null,
});
export const Investment = IDL.Record({
  'id' : IDL.Text,
  'txnIdText' : IDL.Opt(IDL.Text),
  'mode' : IDL.Text,
  'name' : IDL.Text,
  'eProject' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'created_at' : IDL.Int,
  'txnIdNat' : IDL.Nat,
  'investor' : IDL.Principal,
});
export const SessionState = IDL.Record({
  'session_id' : IDL.Text,
  'user_id' : IDL.Principal,
  'timestamp' : IDL.Int,
  'finalRootHash' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transaction_type' : TransactionType,
  'session_seq' : IDL.Nat,
  'txnIdText' : IDL.Opt(IDL.Text),
  'mode' : IDL.Text,
  'txn_hash' : IDL.Text,
  'investment_id' : IDL.Text,
  'investor_id' : IDL.Principal,
  'nonce' : IDL.Text,
  'timestamp' : IDL.Int,
  'txnIdNat' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInvestment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'createTransaction' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        TransactionType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'getAllInvestments' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
  'getAllSessionStates' : IDL.Func([], [IDL.Vec(SessionState)], ['query']),
  'getCallerTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvestment' : IDL.Func([IDL.Text], [IDL.Opt(Investment)], ['query']),
  'getInvestmentList' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Investment)],
      ['query'],
    ),
  'getInvestmentTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getInvestorTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getLatestSessionHashes' : IDL.Func([], [IDL.Opt(SessionState)], ['query']),
  'getSessionIdReturn' : IDL.Func([IDL.Null], [IDL.Opt(IDL.Text)], ['query']),
  'getSessionState' : IDL.Func([IDL.Text], [IDL.Opt(SessionState)], ['query']),
  'getSessionTxnHashes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSessionIdReturn' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateLatestSessionHashes' : IDL.Func([SessionState], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'returnFunds' : IDL.Null,
    'withdraw' : IDL.Null,
    'arbitration' : IDL.Null,
    'instantBuy' : IDL.Null,
    'recharge' : IDL.Null,
    'instantBuyReturn' : IDL.Null,
    'invest' : IDL.Null,
    'payout' : IDL.Null,
  });
  const Investment = IDL.Record({
    'id' : IDL.Text,
    'txnIdText' : IDL.Opt(IDL.Text),
    'mode' : IDL.Text,
    'name' : IDL.Text,
    'eProject' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'created_at' : IDL.Int,
    'txnIdNat' : IDL.Nat,
    'investor' : IDL.Principal,
  });
  const SessionState = IDL.Record({
    'session_id' : IDL.Text,
    'user_id' : IDL.Principal,
    'timestamp' : IDL.Int,
    'finalRootHash' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transaction_type' : TransactionType,
    'session_seq' : IDL.Nat,
    'txnIdText' : IDL.Opt(IDL.Text),
    'mode' : IDL.Text,
    'txn_hash' : IDL.Text,
    'investment_id' : IDL.Text,
    'investor_id' : IDL.Principal,
    'nonce' : IDL.Text,
    'timestamp' : IDL.Int,
    'txnIdNat' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInvestment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'createTransaction' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          TransactionType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'getAllInvestments' : IDL.Func([], [IDL.Vec(Investment)], ['query']),
    'getAllSessionStates' : IDL.Func([], [IDL.Vec(SessionState)], ['query']),
    'getCallerTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvestment' : IDL.Func([IDL.Text], [IDL.Opt(Investment)], ['query']),
    'getInvestmentList' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Investment)],
        ['query'],
      ),
    'getInvestmentTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getInvestorTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getLatestSessionHashes' : IDL.Func([], [IDL.Opt(SessionState)], ['query']),
    'getSessionIdReturn' : IDL.Func([IDL.Null], [IDL.Opt(IDL.Text)], ['query']),
    'getSessionState' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SessionState)],
        ['query'],
      ),
    'getSessionTxnHashes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTransaction' : IDL.Func([IDL.Text], [IDL.Opt(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSessionIdReturn' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateLatestSessionHashes' : IDL.Func([SessionState], [], []),
  });
};

export const init = ({ IDL }) => { return []; };