/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Investment {
  'id' : string,
  'txnIdText' : [] | [string],
  'mode' : string,
  'name' : string,
  'eProject' : [] | [string],
  'description' : string,
  'created_at' : bigint,
  'txnIdNat' : bigint,
  'investor' : Principal,
}
export interface Resource {
  'id' : bigint,
  'title' : string,
  'content' : string,
}
export interface ResourcesPageContent { 'content' : string }
export interface SessionState {
  'session_id' : string,
  'user_id' : Principal,
  'timestamp' : bigint,
  'finalRootHash' : string,
}
export interface Transaction {
  'id' : string,
  'transaction_type' : TransactionType,
  'session_seq' : bigint,
  'txnIdText' : [] | [string],
  'mode' : string,
  'txn_hash' : string,
  'investment_id' : string,
  'investor_id' : Principal,
  'nonce' : string,
  'timestamp' : bigint,
  'txnIdNat' : bigint,
  'amount' : bigint,
}
export type TransactionType = { 'returnFunds' : null } |
  { 'withdraw' : null } |
  { 'arbitration' : null } |
  { 'instantBuy' : null } |
  { 'recharge' : null } |
  { 'instantBuyReturn' : null } |
  { 'invest' : null } |
  { 'payout' : null };
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInvestment' : ActorMethod<
    [string, string, string, [] | [string], string, bigint, [] | [string]],
    undefined
  >,
  'createTransaction' : ActorMethod<
    [
      string,
      string,
      bigint,
      TransactionType,
      string,
      string,
      string,
      bigint,
      [] | [string],
    ],
    undefined
  >,
  'getAllInvestments' : ActorMethod<[], Array<Investment>>,
  'getAllSessionStates' : ActorMethod<[], Array<SessionState>>,
  'getCallerTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvestment' : ActorMethod<[string], [] | [Investment]>,
  'getInvestmentList' : ActorMethod<[Principal], Array<Investment>>,
  'getInvestmentTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getInvestorTransactions' : ActorMethod<[Principal], Array<Transaction>>,
  'getLatestSessionHashes' : ActorMethod<[], [] | [SessionState]>,
  'getResource' : ActorMethod<[bigint], [] | [Resource]>,
  'getResourcesPageContent' : ActorMethod<[], ResourcesPageContent>,
  'getSessionIdReturn' : ActorMethod<[null], [] | [string]>,
  'getSessionState' : ActorMethod<[string], [] | [SessionState]>,
  'getSessionTxnHashes' : ActorMethod<[], Array<string>>,
  'getTransaction' : ActorMethod<[string], [] | [Transaction]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSessionIdReturn' : ActorMethod<[string, string], undefined>,
  'updateLatestSessionHashes' : ActorMethod<[SessionState], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];