/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SessionState {
    session_id: string;
    user_id: Principal;
    timestamp: bigint;
    finalRootHash: string;
}
export interface Investment {
    id: string;
    name: string;
    eProject?: string;
    description: string;
    created_at: bigint;
    investor: Principal;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface Transaction {
    id: string;
    transaction_type: TransactionType;
    session_seq: bigint;
    txnIdText?: string;
    mode: string;
    txn_hash: string;
    investment_id: string;
    investor_id: Principal;
    nonce: string;
    timestamp: bigint;
    txnIdNat: bigint;
    amount: bigint;
}
export enum TransactionType {
    returnFunds = "returnFunds",
    withdraw = "withdraw",
    arbitration = "arbitration",
    instantBuy = "instantBuy",
    recharge = "recharge",
    instantBuyReturn = "instantBuyReturn",
    invest = "invest",
    payout = "payout"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createInvestment(id: string, name: string, description: string, eProject: string | null): Promise<void>;
    createTransaction(id: string, investment_id: string, amount: bigint, transaction_type: TransactionType, txn_hash: string, sessionId: string, mode: string, txnIdNat: bigint, txnIdText: string | null): Promise<void>;
    getAllInvestments(): Promise<Array<Investment>>;
    getAllSessionStates(): Promise<Array<SessionState>>;
    getCallerTransactions(): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInvestment(id: string): Promise<Investment | null>;
    getInvestmentList(p: Principal): Promise<Array<Investment>>;
    getInvestmentTransactions(investment_id: string): Promise<Array<Transaction>>;
    getInvestorTransactions(investor_id: Principal): Promise<Array<Transaction>>;
    getLatestSessionHashes(): Promise<SessionState | null>;
    getSessionIdReturn(arg0: null): Promise<string | null>;
    getSessionState(session_id: string): Promise<SessionState | null>;
    getSessionTxnHashes(): Promise<Array<string>>;
    getTransaction(id: string): Promise<Transaction | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setSessionIdReturn(id: string, nonce: string): Promise<void>;
    updateLatestSessionHashes(sessionState: SessionState): Promise<void>;
}
import type { Investment as _Investment, SessionState as _SessionState, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createInvestment(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvestment(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvestment(arg0, arg1, arg2, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createTransaction(arg0: string, arg1: string, arg2: bigint, arg3: TransactionType, arg4: string, arg5: string, arg6: string, arg7: bigint, arg8: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransaction(arg0, arg1, arg2, to_candid_TransactionType_n4(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransaction(arg0, arg1, arg2, to_candid_TransactionType_n4(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async getAllInvestments(): Promise<Array<Investment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvestments();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvestments();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSessionStates(): Promise<Array<SessionState>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessionStates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessionStates();
            return result;
        }
    }
    async getCallerTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTransactions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTransactions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestment(arg0: string): Promise<Investment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestment(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestment(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestmentList(arg0: Principal): Promise<Array<Investment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestmentList(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestmentList(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestmentTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestmentTransactions(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestmentTransactions(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvestorTransactions(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvestorTransactions(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvestorTransactions(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestSessionHashes(): Promise<SessionState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestSessionHashes();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestSessionHashes();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionIdReturn(arg0: null): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionIdReturn(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionIdReturn(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionState(arg0: string): Promise<SessionState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionState(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionState(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionTxnHashes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionTxnHashes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionTxnHashes();
            return result;
        }
    }
    async getTransaction(arg0: string): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setSessionIdReturn(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSessionIdReturn(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSessionIdReturn(arg0, arg1);
            return result;
        }
    }
    async updateLatestSessionHashes(arg0: SessionState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLatestSessionHashes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLatestSessionHashes(arg0);
            return result;
        }
    }
}
function from_candid_Investment_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Investment): Investment {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Investment]): Investment | null {
    return value.length === 0 ? null : from_candid_Investment_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionState]): SessionState | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transaction_type: _TransactionType;
    session_seq: bigint;
    txnIdText: [] | [string];
    mode: string;
    txn_hash: string;
    investment_id: string;
    investor_id: Principal;
    nonce: string;
    timestamp: bigint;
    txnIdNat: bigint;
    amount: bigint;
}): {
    id: string;
    transaction_type: TransactionType;
    session_seq: bigint;
    txnIdText?: string;
    mode: string;
    txn_hash: string;
    investment_id: string;
    investor_id: Principal;
    nonce: string;
    timestamp: bigint;
    txnIdNat: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        transaction_type: from_candid_TransactionType_n13(_uploadFile, _downloadFile, value.transaction_type),
        session_seq: value.session_seq,
        txnIdText: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.txnIdText)),
        mode: value.mode,
        txn_hash: value.txn_hash,
        investment_id: value.investment_id,
        investor_id: value.investor_id,
        nonce: value.nonce,
        timestamp: value.timestamp,
        txnIdNat: value.txnIdNat,
        amount: value.amount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    eProject: [] | [string];
    description: string;
    created_at: bigint;
    investor: Principal;
}): {
    id: string;
    name: string;
    eProject?: string;
    description: string;
    created_at: bigint;
    investor: Principal;
} {
    return {
        id: value.id,
        name: value.name,
        eProject: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.eProject)),
        description: value.description,
        created_at: value.created_at,
        investor: value.investor
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    returnFunds: null;
} | {
    withdraw: null;
} | {
    arbitration: null;
} | {
    instantBuy: null;
} | {
    recharge: null;
} | {
    instantBuyReturn: null;
} | {
    invest: null;
} | {
    payout: null;
}): TransactionType {
    return "returnFunds" in value ? TransactionType.returnFunds : "withdraw" in value ? TransactionType.withdraw : "arbitration" in value ? TransactionType.arbitration : "instantBuy" in value ? TransactionType.instantBuy : "recharge" in value ? TransactionType.recharge : "instantBuyReturn" in value ? TransactionType.instantBuyReturn : "invest" in value ? TransactionType.invest : "payout" in value ? TransactionType.payout : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Investment>): Array<Investment> {
    return value.map((x)=>from_candid_Investment_n7(_uploadFile, _downloadFile, x));
}
function to_candid_TransactionType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    returnFunds: null;
} | {
    withdraw: null;
} | {
    arbitration: null;
} | {
    instantBuy: null;
} | {
    recharge: null;
} | {
    instantBuyReturn: null;
} | {
    invest: null;
} | {
    payout: null;
} {
    return value == TransactionType.returnFunds ? {
        returnFunds: null
    } : value == TransactionType.withdraw ? {
        withdraw: null
    } : value == TransactionType.arbitration ? {
        arbitration: null
    } : value == TransactionType.instantBuy ? {
        instantBuy: null
    } : value == TransactionType.recharge ? {
        recharge: null
    } : value == TransactionType.instantBuyReturn ? {
        instantBuyReturn: null
    } : value == TransactionType.invest ? {
        invest: null
    } : value == TransactionType.payout ? {
        payout: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
